varReference:
- kind: Deployment
  path: spec/template/spec/containers/image
- kind: Deployment
  path: spec/template/spec/initContainers/args
- kind: Job
  path: spec/template/spec/containers/image
- kind: Job
  path: metadata/name
- kind: Ingress
  path: spec/rules/host
