apiVersion: v1
kind: ServiceAccount
metadata:
  name: hello
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hello
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hello
subjects:
  - kind: ServiceAccount
    name: hello
roleRef:
  kind: Role
  name: hello
  apiGroup: rbac.authorization.k8s.io
