apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-prod

resources:
  - ../../base

patches:
  - hello-deploy.yaml

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
    - APP_ENV=prod
